# Generated by Django 5.2.3 on 2026-02-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_itemreport_unique_together_alter_item_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
