# Generated by Django 6.0 on 2025-12-31 15:15

import _hashlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_registrationotp_remove_user_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationotp',
            name='otp',
        ),
        migrations.AddField(
            model_name='registrationotp',
            name='otp_hash',
            field=models.CharField(default=_hashlib.openssl_sha256, max_length=128),
        ),
    ]
