# Generated by Django 6.0 on 2025-12-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_registrationotp_otp_registrationotp_otp_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationotp',
            name='otp_hash',
            field=models.CharField(max_length=128),
        ),
    ]
