# Generated by Django 6.0 on 2026-01-01 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_registrationotp_otp_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verified',
            new_name='is_verified',
        ),
    ]
