# Generated by Django 5.2.3 on 2026-02-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_registrationotp_id_alter_user_id_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='items_reported_found',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='items_reported_missing',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
