# Generated by Django 5.2.3 on 2026-02-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
