# Generated by Django 6.0.2 on 2026-02-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_registrationotp_id_alter_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_on_new_messages',
            field=models.BooleanField(default=True),
        ),
    ]
