# Generated by Django 6.0.2 on 2026-02-25 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_notification_on_new_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='notification_on_new_messages',
        ),
    ]
