# Generated by Django 6.0.2 on 2026-02-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_user_notification_on_new_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_on_new_messages',
            field=models.BooleanField(default=True),
        ),
    ]
